//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MicroData.Base.UI.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BaseStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BaseStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MicroData.Base.UI.Resource.BaseStrings", typeof(BaseStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barkod.
        /// </summary>
        public static string BarCode {
            get {
                return ResourceManager.GetString("BarCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poslovni Partner.
        /// </summary>
        public static string BusinessPartner {
            get {
                return ResourceManager.GetString("BusinessPartner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izmena jedinice.
        /// </summary>
        public static string ChangeUnit {
            get {
                return ResourceManager.GetString("ChangeUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klijent.
        /// </summary>
        public static string Client {
            get {
                return ResourceManager.GetString("Client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Šifra.
        /// </summary>
        public static string CodeName {
            get {
                return ResourceManager.GetString("CodeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Šifra je obavezno polje.
        /// </summary>
        public static string CodeRequired {
            get {
                return ResourceManager.GetString("CodeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Šifra.
        /// </summary>
        public static string CodeUnits {
            get {
                return ResourceManager.GetString("CodeUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valuta.
        /// </summary>
        public static string Currency {
            get {
                return ResourceManager.GetString("Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obriši.
        /// </summary>
        public static string DeleteUnits {
            get {
                return ResourceManager.GetString("DeleteUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opis.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dokumenat.
        /// </summary>
        public static string Document {
            get {
                return ResourceManager.GetString("Document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izmeni.
        /// </summary>
        public static string EditUnits {
            get {
                return ResourceManager.GetString("EditUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zaposleni.
        /// </summary>
        public static string Employee {
            get {
                return ResourceManager.GetString("Employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ime.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merkantilan Roba.
        /// </summary>
        public static string Grain {
            get {
                return ResourceManager.GetString("Grain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tabela jedinica.
        /// </summary>
        public static string HeaderUnit {
            get {
                return ResourceManager.GetString("HeaderUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zdravo Svete - Srpski.
        /// </summary>
        public static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unseite adresu.
        /// </summary>
        public static string InsertAddress {
            get {
                return ResourceManager.GetString("InsertAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unseite barkod.
        /// </summary>
        public static string InsertBarcode {
            get {
                return ResourceManager.GetString("InsertBarcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unesite poslovnog partnera.
        /// </summary>
        public static string InsertBusinessPartner {
            get {
                return ResourceManager.GetString("InsertBusinessPartner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unesite sedište.
        /// </summary>
        public static string InsertCity {
            get {
                return ResourceManager.GetString("InsertCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unesite šifru.
        /// </summary>
        public static string InsertCode {
            get {
                return ResourceManager.GetString("InsertCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unesite dokumenat.
        /// </summary>
        public static string InsertDocument {
            get {
                return ResourceManager.GetString("InsertDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsite email .
        /// </summary>
        public static string InsertEmail {
            get {
                return ResourceManager.GetString("InsertEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unesite merkantilnu robu.
        /// </summary>
        public static string InsertGrain {
            get {
                return ResourceManager.GetString("InsertGrain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unesite naziv.
        /// </summary>
        public static string InsertName {
            get {
                return ResourceManager.GetString("InsertName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unesite napomena.
        /// </summary>
        public static string InsertNote {
            get {
                return ResourceManager.GetString("InsertNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsite kontakt telefon.
        /// </summary>
        public static string InsertPhone {
            get {
                return ResourceManager.GetString("InsertPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unesite matični broj.
        /// </summary>
        public static string InsertRegistryNumber {
            get {
                return ResourceManager.GetString("InsertRegistryNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unesite prevoznika.
        /// </summary>
        public static string InsertShipper {
            get {
                return ResourceManager.GetString("InsertShipper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unesite državu.
        /// </summary>
        public static string InsertState {
            get {
                return ResourceManager.GetString("InsertState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unesite PIB.
        /// </summary>
        public static string InsertTaxNumber {
            get {
                return ResourceManager.GetString("InsertTaxNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unisite internet stranicu.
        /// </summary>
        public static string InsertWww {
            get {
                return ResourceManager.GetString("InsertWww", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktivna.
        /// </summary>
        public static string IsActiveName {
            get {
                return ResourceManager.GetString("IsActiveName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Da li je aktivna jedinica?.
        /// </summary>
        public static string IsActiveUnits {
            get {
                return ResourceManager.GetString("IsActiveUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oznaka.
        /// </summary>
        public static string LabelName {
            get {
                return ResourceManager.GetString("LabelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oznaka je obavezno polje.
        /// </summary>
        public static string LabelRequired {
            get {
                return ResourceManager.GetString("LabelRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oznaka.
        /// </summary>
        public static string LabelUnits {
            get {
                return ResourceManager.GetString("LabelUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prezime.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lokacija.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naziv.
        /// </summary>
        public static string NameName {
            get {
                return ResourceManager.GetString("NameName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naziv je obavezno polje.
        /// </summary>
        public static string NameRequired {
            get {
                return ResourceManager.GetString("NameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naziv.
        /// </summary>
        public static string NameUnits {
            get {
                return ResourceManager.GetString("NameUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novi.
        /// </summary>
        public static string NewUnits {
            get {
                return ResourceManager.GetString("NewUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Napomena.
        /// </summary>
        public static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cena.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roba.
        /// </summary>
        public static string Product {
            get {
                return ResourceManager.GetString("Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usluga.
        /// </summary>
        public static string Service {
            get {
                return ResourceManager.GetString("Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prevoznik.
        /// </summary>
        public static string Shipper {
            get {
                return ResourceManager.GetString("Shipper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Porez.
        /// </summary>
        public static string Tax {
            get {
                return ResourceManager.GetString("Tax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopa PDV-a.
        /// </summary>
        public static string TaxRate {
            get {
                return ResourceManager.GetString("TaxRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jedinica Mere.
        /// </summary>
        public static string Unit {
            get {
                return ResourceManager.GetString("Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vrednost od.
        /// </summary>
        public static string ValueFrom {
            get {
                return ResourceManager.GetString("ValueFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vrednost do.
        /// </summary>
        public static string ValueTo {
            get {
                return ResourceManager.GetString("ValueTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skladište.
        /// </summary>
        public static string Warehouse {
            get {
                return ResourceManager.GetString("Warehouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radno Mesto.
        /// </summary>
        public static string WorkPlace {
            get {
                return ResourceManager.GetString("WorkPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radna Smena.
        /// </summary>
        public static string WorkShift {
            get {
                return ResourceManager.GetString("WorkShift", resourceCulture);
            }
        }
    }
}
